### ISSUE TITLE
Question:  why is there almost duplicate data objects for different image sides?

### ISSUE THREAD

**Issue by DimitriTsikaridze** [any2cards/jotl#4]
I don't understand why is there two objects that have same data except image and point
wouldn't it be better to have both images in single character mat object like 'imageFront' and 'imageBack' ? seems like extra code for me just for the sake of having different image path 

```
{
    "name": "demolitionist",
    "points": 0,
    "expansion": "Jaws Of The Lion",
    "image": "character-mats/jaws-of-the-lion/jl-demolitionist-front.png",
    "xws": "demolitionist"
  },
  {
    "name": "demolitionist",
    "points": 1,
    "expansion": "Jaws Of The Lion",
    "image": "character-mats/jaws-of-the-lion/jl-demolitionist-back.png",
    "xws": "demolitionist"
}

**Comment by any2cards** [comment]
The asset viewer works based off of key names.  A key name is found within a specific site's webpage, and it is underlined.  I use the same key name when there are multiple object images that apply to that key name.  This is how the viewer actually works.  This is not an issue, but a feature.  I am sorry that it does not work well for whatever purpose you are leveraging the JSON for, but it is required for my use.
